<a href="https://colab.research.google.com/github/advait2811/pytorch/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [2]:
import numpy as np


In [3]:
tensor2d= torch.rand(27)
tensor2d

tensor([0.9428, 0.4686, 0.0935, 0.3497, 0.5131, 0.2634, 0.7885, 0.7394, 0.5868,
        0.0151, 0.0498, 0.3335, 0.7075, 0.0237, 0.0957, 0.4584, 0.5586, 0.4078,
        0.7869, 0.3606, 0.5277, 0.3063, 0.0563, 0.3790, 0.7101, 0.7012, 0.2442])

In [4]:
tensor2d=tensor2d.reshape(-1,3)
tensor2d

tensor([[0.9428, 0.4686, 0.0935],
        [0.3497, 0.5131, 0.2634],
        [0.7885, 0.7394, 0.5868],
        [0.0151, 0.0498, 0.3335],
        [0.7075, 0.0237, 0.0957],
        [0.4584, 0.5586, 0.4078],
        [0.7869, 0.3606, 0.5277],
        [0.3063, 0.0563, 0.3790],
        [0.7101, 0.7012, 0.2442]])

In [16]:
tensor3d=torch.zeros(3,3,3)
tensor3d


tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [18]:
tensora=torch.tensor([1,2,3,4,5])
tensorb=torch.tensor([6,7,2,11,111])

In [22]:
print(tensora+tensorb)
print(tensora.add(tensorb))
print(tensora.pow(tensorb))
print(torch.add(tensora,tensorb))

tensor([  7,   9,   5,  15, 116])
tensor([  7,   9,   5,  15, 116])
tensor([                   1,                  128,                    9,
                     4194304, -6702486051151591923])
tensor([  7,   9,   5,  15, 116])
